#!/bin/bash

domain=$1
curl -s https://crt.sh/?q\=$domain\&output\=json | jq -r '.[].name_value' | sort -u | grep -v '*'
curl -s https://crt.sh/?q\=%.$domain\&output\=json | jq -r '.[].name_value' | sort -u | grep -v '*'
curl -s https://crt.sh/?q\=%.%.$domain\&output\=json | jq -r '.[].name_value' | sort -u | grep -v '*'
curl -s https://crt.sh/?q\=%.%.%.$domain\&output\=json | jq -r '.[].name_value' | sort -u | grep -v '*'
curl -s https://crt.sh/?q\=%.%.%.%.$domain\&output\=json | jq -r '.[].name_value' | sort -u | grep -v '*'
