#!/bin/bash

while getopts ":h:" input;do
        case "$input" in
                h) host=${OPTARG}
                        ;;
                esac
        done
if [ -z "$host" ]     
        then
                echo "Please give a domain like \"-h http(s)://host.com\""
                exit 1
fi

curl -I -s -L $host | grep -iE 'Content-Security|CSP' | sed 's/ /\n/g' | grep -E '\.' | unfurl format %d | sed 's/\*\.//g' | sed 's/;$//g' | sort -u
