#!/bin/bash
domain=$1
for subdomain in $(curl -s https://api.securitytrails.com/v1/domain/$domain/subdomains?apikey=bxgpXoF2l19IMtRMSTBYq0RZIlZlzxjg | jq '.subdomains[]' | sed 's/\"//g'); do echo $subdomain.$domain; done
