#!/bin/bash
domain=$1
for subdomain in $(curl -s https://api.securitytrails.com/v1/domain/$domain/subdomains?apikey=iW0n882JXJ8FzRO4K1n70PJHBygQir4U | jq '.subdomains[]' | sed 's/\"//g'); do echo $subdomain.$domain; done
